### PR TITLE
Update 2015-06-18-run-xcode-7-ui-tests-from-the-command-line.md

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
add a brief note at the end for how Xcode 9 users can still use this suggestion

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @monkeywithacupcake, thanks for the PR, I appreciate it. Actually I'm ok with just updating the "original" command from the post, can you update the PR to fix the command that's currently being described to work with the new Xcode release? Thanks

**Comment by monkeywithacupcake** [comment]
Ok. I changed it. Also, I'm loving fastlane - what a great idea.

**Review by KrauseFx — APPROVED** [review]
Beautiful, thank you so much 👍 ❤️ @monkeywithacupcake

**Comment by KrauseFx** [comment]
So glad to hear 👍

**Pull request merged**
